test: Fully migrate and run integration tests
Keep most of the structure intact, just clean-up everything that we
don't need and adjust the tests.

Ticket: QA-1215

Signed-off-by: Lluis Campos <lluis.campos@northern.tech>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -55,11 +55,16 @@ variables:
 
   DOCKER_VERSION: "28.1"
 
+  XDIST_WORKERS_INTEGRATION_TEST:
+    description: "Number of workers to spawn in pytest-xdist and use in the integration tests"
+    value: 4
+
 stages:
   - build
   - test
   - test_acceptance_build
   - test_acceptance
+  - test_integration
   - publish
   - changelog
 
@@ -141,6 +146,54 @@ test_acceptance:run:
     expire_in: 1w
     paths:
       - tests/acceptance/coverage
+
+.requires-docker: &requires-docker
+  - DOCKER_RETRY_SLEEP_S=2
+  - DOCKER_RUNNING=false
+  - for try in 4 3 2 1; do
+  -  docker ps && DOCKER_RUNNING=true
+  -  if [ "${DOCKER_RUNNING}" == "true" ]; then
+  -   break
+  -  fi
+  -  sleep "${DOCKER_RETRY_SLEEP_S}"
+  - done
+  - if [ "${DOCKER_RUNNING}" != "true" ]; then
+  -  exit 192
+  - fi
+
+test:integration:
+  stage: test_integration
+  tags:
+    - hetzner-amd-beefy
+  variables:
+    GIT_SUBMODULE_STRATEGY: recursive
+    GIT_SUBMODULE_DEPTH: 1
+  image: docker:${DOCKER_VERSION}
+  needs:
+    - compile
+  before_script:
+    # TODO: move to submodule and unify with acceptance tests
+    - git clone https://github.com/mendersoftware/mender-server tests/integration/mender_server
+    - mkdir -p $HOME/.docker
+    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
+    - apk add --update bash cmake curl dpkg e2fsprogs-extra g++ gcompat gcompat git iptables jq libffi-dev make openssh-client py3-pip python3-dev zstd screen openssl-dev openssl-libs-static
+    # Workaround for "Failed building wheel for uamqp" error
+    - CFLAGS="-Wno-error=incompatible-pointer-types" CMAKE_POLICY_VERSION_MINIMUM=3.5 pip install uamqp --break-system-packages
+    - pip install --ignore-installed -r tests/integration/mender_server/backend/tests/requirements-integration.txt --break-system-packages
+    - pip install -r tests/integration/requirements.txt --break-system-packages
+    # Gitlab CI tends to set these DOCKER_ variables internally.
+    # dind also creates the unix socket at /var/run/docker.sock
+    # This docker setup is based on `.gitlab-ci-full-integration-template.yml`
+    # from integration
+    - unset DOCKER_HOST DOCKER_TLS_VERIFY DOCKER_CERT_PATH
+    # Run dockerd and wait it to start
+    # https://github.com/krallin/tini#subreaping
+    - screen -d -m /usr/bin/env TINI_SUBREAPER=true dockerd-entrypoint.sh
+    - *requires-docker
+  script:
+    - mv mender-cli.linux.amd64 /usr/local/bin/mender-cli
+    - cd tests/integration
+    - ./run_tests.sh -n ${XDIST_WORKERS_INTEGRATION_TEST}
 
 test:install:brew:
   stage: test
